# Patient Data 'provsvar' Data Visualization Interfaces in Python With Dash

[source](https://realpython.com/python-dash/)

Installation:
```
* python3 -m venv env #create a virtual environment venv called env (in Windows)
* env\scripts\activate #activate the venv instead of source env/bin/activate in other systems
```

In [2]:
import dash
#import dash_core_components as dcc
from dash import dcc
#import dash_html_components as html
from dash import html
import pandas as pd

In [3]:
data = pd.read_csv("https://raw.githubusercontent.com/dnzengou/provsvar_notebook/main/data/provsvar_sept_anonym_122021-Blad11_mal_full.csv")

In [6]:
# data cleaning

# renaming the df column names to lowercase
data.columns = map(str.lower, data.columns)

data.head()

,personnummer,provsvarsdate,provsvar 1,värde 1,bedömning 1,provsvar 2,värde 2,bedömning 2,provsvar 3,värde 3,bedömning 3,provsvar 4,värde 4,bedömning 4,provsvar 5,värde 5,bedömning 5,total bedomning
0,8201113128,22/12/2021,"T4, fritt, P-",13,GRON,"T3, fritt, P-",4.50,GRON,"TSH, P-",1.0,GRON,"ASAT, P-",0.49,GRON,"ALAT, P-",0.64,GRON,GRON
1,8201113131,15/12/2021,"T4, fritt, P-",17,GRON,"T3, P-",0.76,GUL,"TSH, P-",2.8,GRON,"ASAT, P-",0.59,GRON,"ALAT, P-",0.60,GRON,GUL
2,8201113134,14/12/2021,"T4, fritt, P-",16,GRON,"T3, P-",1.10,GRON,"TSH, P-",5.1,GUL,"ASAT, P-",0.40,GRON,"ALAT, P-",0.28,GRON,GRON
3,8201113137,13/12/2021,"T4, fritt, P-",16,GRON,"T3, P-",1.00,GRON,"TSH, P-",1.8,GRON,"ASAT, P-",0.30,GRON,"ALAT, P-",0.27,GRON,GRON
4,8201113140,18/12/2021,"T4, fritt, P-",15,GRON,"T3, P-",1.30,GRON,"TSH, P-",1.1,GRON,"ASAT, P-",0.33,GRON,"ALAT, P-",0.18,GRON,GRON

In [7]:
data.rename(columns = {'provsvar 1':'provsvar1', 'provsvar 2':'provsvar2', 'provsvar 3':'provsvar3', 'provsvar 4':'provsvar4', 'provsvar 5':'provsvar5', 'provsvar 6':'provsvar6', 'värde 1':'varde1', 'värde 2':'varde2', 'värde 3':'varde3', 'värde 4':'varde4', 'värde 5':'varde5',
                              'värde 6':'varde6', 'bedömning 1':'bedomning1', 'bedömning 2':'bedomning2', 'bedömning 3':'bedomning3', 'bedömning 4':'bedomning4', 'bedömning 5':'bedomning5', 'total bedomning':'total_bedomning'}, inplace = True)

In [9]:
data.head()

,personnummer,provsvarsdate,provsvar1,varde1,bedomning1,provsvar2,varde2,bedomning2,provsvar3,varde3,bedomning3,provsvar4,varde4,bedomning4,provsvar5,varde5,bedomning5,total_bedomning
0,8201113128,22/12/2021,"T4, fritt, P-",13,GRON,"T3, fritt, P-",4.50,GRON,"TSH, P-",1.0,GRON,"ASAT, P-",0.49,GRON,"ALAT, P-",0.64,GRON,GRON
1,8201113131,15/12/2021,"T4, fritt, P-",17,GRON,"T3, P-",0.76,GUL,"TSH, P-",2.8,GRON,"ASAT, P-",0.59,GRON,"ALAT, P-",0.60,GRON,GUL
2,8201113134,14/12/2021,"T4, fritt, P-",16,GRON,"T3, P-",1.10,GRON,"TSH, P-",5.1,GUL,"ASAT, P-",0.40,GRON,"ALAT, P-",0.28,GRON,GRON
3,8201113137,13/12/2021,"T4, fritt, P-",16,GRON,"T3, P-",1.00,GRON,"TSH, P-",1.8,GRON,"ASAT, P-",0.30,GRON,"ALAT, P-",0.27,GRON,GRON
4,8201113140,18/12/2021,"T4, fritt, P-",15,GRON,"T3, P-",1.30,GRON,"TSH, P-",1.1,GRON,"ASAT, P-",0.33,GRON,"ALAT, P-",0.18,GRON,GRON

In [8]:
#  asexport csv
data.to_csv('../data/provsvar_sept_anonym_122021-Blad11_mal_full_clean.csv', index=False)

In [12]:
data = data.query("total_bedomning == 'GRON'")
data["provsvarsdate"] = pd.to_datetime(data["provsvarsdate"], format="%d/%m/%Y")
data.sort_values("provsvarsdate", inplace=True)

# create an instance of the Dash class: nitializing a Dash class by initializing a WSGI application using Dash(__name__)
app = dash.Dash(__name__)

emoji [source](https://emojipedia.org/woman-health-worker-medium-skin-tone/)

In [6]:
app.layout = html.Div(
    children=[
        html.H1(children="Patient Provsvar Analytics",),
        html.P(
            children="Analyze the behavior of patient provsvar"
            " and the number of GRON bedömning"
            " over time",
        ),
        dcc.Graph(
            figure={
                "data": [
                    {
                        "x": data["provsvarsdate"],
                        "y": data["varde1"],
                        "type": "lines",
                    },
                ],
                "layout": {"title": "Värde 1 över tiden"},
            },
        ),
        dcc.Graph(
            figure={
                "data": [
                    {
                        "x": data["provsvarsdate"],
                        "y": data["varde2"],
                        "type": "bars",
                    },
                ],
                "layout": {"title": "Värde 2 över tiden"},
            },
        ),
        dcc.Graph(
            figure={
                "data": [
                    {
                        "x": data["provsvarsdate"],
                        "y": data["varde2"],
                        "type": "lines",
                    },
                ],
                "layout": {"title": "Värde 2 över tiden"},
            },
        ),
        dcc.Graph(
            figure={
                "data": [
                    {
                        "x": data["provsvarsdate"],
                        "y": data["varde3"],
                        "type": "lines",
                    },
                ],
                "layout": {"title": "Värde 3 över tiden"},
            },
        ),
        dcc.Graph(
            figure={
                "data": [
                    {
                        "x": data["provsvarsdate"],
                        "y": data["varde4"],
                        "type": "lines",
                    },
                ],
                "layout": {"title": "Värde 4 över tiden"},
            },
        ),
        dcc.Graph(
            figure={
                "data": [
                    {
                        "x": data["provsvarsdate"],
                        "y": data["varde5"],
                        "type": "lines",
                    },
                ],
                "layout": {"title": "Värde 5 över tiden"},
            },
        ),
    ]
)

In [7]:
if __name__ == "__main__":
    app.run_server(debug=True)

Dash is running on http://127.0.0.1:8050/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on

SystemExit: 1

C:\Users\DSINZ1\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3445: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)